WEB_153505_PIKHTOVNIKAVA/WEB_153505_PIKHTOVNIKAVA/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WEB_153505_PIKHTOVNIKAVA.Domain.Models;
using WEB_153505_PIKHTOVNIKAVA.Services.ProductService;

namespace WEB_153505_PIKHTOVNIKAVA.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductService _productService;
        private readonly Cart _cart;

        public CartController(IProductService productService, Cart cart)
        {
            _productService = productService;
            _cart = cart;
        }

        [Authorize]
        [Route("[controller]/add/{id:int}")]
        public async Task<ActionResult> Add(int id, string ReturnUrl)
        {
            var response = (await _productService.GetProductByIdAsync(id));
            if (response.Success)
                _cart.AddToCart(response.Data);
            return Redirect(ReturnUrl);
        }

        [Authorize]
        [Route("[controller]/")]
        public async Task<ActionResult> Index()
        {
            return View(_cart.CartItems);
        }

        [Authorize]
        [Route("[controller]/delete/{id:int}")]
        public async Task<ActionResult> Delete(int id, string ReturnUrl)
        {
            _cart.RemoveItems(id);
            return Redirect(ReturnUrl);
        }
    }
}

WEB_153505_PIKHTOVNIKAVA/WEB_153505_PIKHTOVNIKAVA/Controllers/IdentityController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WEB_153505_PIKHTOVNIKAVA.Controllers
{
    public class IdentityController : Controller
    {
        public async Task Login()
        {
            await HttpContext.ChallengeAsync(
            "oidc",
            new AuthenticationProperties
            {
                RedirectUri =
                    Url.Action("Index", "Home")
            });
        }           

        public async Task Logout()
        {
            await HttpContext.SignOutAsync("cookie");
            await HttpContext.SignOutAsync("oidc",
            new AuthenticationProperties
            {
                RedirectUri =
                      Url.Action("Index", "Home")
            });

        }
    }
}

WEB_153505_PIKHTOVNIKAVA/WEB_153505_PIKHTOVNIKAVA/Controllers/SneakersProductController.cs
using Microsoft.AspNetCore.Mvc;
using WEB_153505_PIKHTOVNIKAVA.Services.ProductService;
using WEB_153505_PIKHTOVNIKAVA.Domain.Models;
using WEB_153505_PIKHTOVNIKAVA.Domain.Entities;
using WEB_153505_PIKHTOVNIKAVA.Extensions;
using WEB_153505_PIKHTOVNIKAVA.Services.SeasonCategoryService;

namespace WEB_153505_PIKHTOVNIKAVA.Controllers
{
    public class SneakersProductController : Controller
    {
        readonly IProductService _productService;
        readonly ISeasonCategoryService _categoryService;


        public SneakersProductController(IProductService productService, ISeasonCategoryService categoryService)
        {
            this._productService = productService;
            this._categoryService = categoryService;
        }


        [Route("Catalog/{category?}", Name = "catalog")]
        public async Task<IActionResult> Index(string? category, int pageno)
        {
            // получаем список кроссовок
            var productResponse =
           await _productService.GetProductListAsync(category, pageno);

            // обработка неуспешного обращения
            if (!productResponse.Success)
                return NotFound(productResponse.ErrorMessage);

            // получаем все категории
            var categories = (await _categoryService.GetCategoryListAsync()).Data;

            // currentCategory вынесено в отдельную переменную, чтобы проверить на null и, в случае null, передать 
            // в представление строку "Все"
            var currentCategory = categories.Find(c => c.NormalizedName == category);


            // чтобы отображать категорию "все", на странице с типами
            ViewData["currentCategory"] = currentCategory == null ? "Все" : currentCategory.Name;
            ViewBag.categories = categories;

            if (Request.IsAjaxRequest())
            {
                return PartialView("_FurnituriesPartial", productResponse.Data);
            }

            return View(productResponse.Data);
        }
    }
}

WEB_153505_PIKHTOVNIKAVA/WEB_153505_PIKHTOVNIKAVA/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEB_153505_PIKHTOVNIKAVA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css"/>
    <link rel="stylesheet" href="~/WEB_153505_PIKHTOVNIKAVA.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                <partial name="_MenuPartial" />
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                <partial name="_UserInfoPartial" />
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
        </div>
    </header>
    <main class="container">
         @RenderBody()

    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
    <footer>
        <div class="container">
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ms-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fa-brands fa-facebook-f fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fa-brands fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fa-brands fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

WEB_153505_PIKHTOVNIKAVA/WEB_153505_PIKHTOVNIKAVA/Views/Shared/_MenuPartial.cshtml
@{
    // достает контролер из маршрута
    var controller = ViewContext.RouteData.Values["controller"]? //Эта строка кода объявляет переменную controller, 
    //которая будет использоваться для хранения имени контроллера,полученного из маршрута. 
    // Это имя будет использоваться для определения текущего контроллера, на котором находится пользователь.
           .ToString()?
           .ToLower()
           ?? String.Empty;

    var area = ViewContext.RouteData.Values["area"]? //Здесь используется ViewContext, 
    //чтобы получить информацию о текущем маршруте. RouteData.Values - это коллекция значений маршрута, 
    //и "controller" - это ключ, который соответствует имени текущего контроллера.
    .ToString()?
    .ToLower()
    ?? String.Empty;
}

   <a class="navbar-brand" asp-controller="Home" asp-action="Index">15350098</a>
    <div class="navbar-nav">
        <a class="nav-item nav-link" asp-controller="Home" asp-action="Index">Лб 1</a>
        <a class="nav-item nav-link" asp-controller="SneakersProduct" asp-action="Index" asp-route-pageno="1">Каталог</a>
        <a class="nav-item nav-link" asp-area="Admin" asp-page="/Index">Администрирование</a>
    </div>

WEB_153505_PIKHTOVNIKAVA/WEB_153505_PIKHTOVNIKAVA/Views/Shared/_ProductCardsPartial.cshtml
@{
    var request = ViewContext.HttpContext.Request;
    var returnUrl = request.Path + request.QueryString.ToUriComponent();
}
<!-- карточки с самолетами начало -->
@foreach (var item in Model.Items)
{
    <div class="col-3">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <img src="@item.PhotoPath" width="300" />
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">@item.Description</p>
                        <a asp-controller="Cart" asp-action="Add"
                       asp-route-id="@item.Id" asp-route-returnurl="@returnUrl"
                       class="btn btn-primary">
                            Добавить в корзину <i class="fa-solid fa-cart-shopping"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<!-- карточки с самолетами конец -->

WEB_153505_PIKHTOVNIKAVA/WEB_153505_PIKHTOVNIKAVA/Views/Shared/_UserInfoPartial.cshtml
@{
    var userEmail = User.Claims.FirstOrDefault(c =>
                c.Type.Equals("Name", StringComparison.OrdinalIgnoreCase))
                ?.Value;
}

@if (User.Identity.IsAuthenticated)
{
    <!-- Информация пользователя -->
    @await Component.InvokeAsync(nameof(WEB_153505_PIKHTOVNIKAVA.ViewComponents.OrderCart))
    <!-- Информация пользователя конец-->
    <!--выпадающий список с инфой о пользователе и кнопкой logout-->
    <div class="dropdown ms-4 nav-color">
        <button class="btn btn-secondary dropdown-toggle"
            type="button" id="dropdownMenuButton"
            data-bs-toggle="dropdown"
            aria-expanded="false">
            @userEmail
            <img src="https://localhost:7003/avatar" width="30"
             alt="User" class="rounded nav-color" />
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li>
                <span class="dropdown-item-text">
                    <img src="https://localhost:7003/avatar"
                     width="50" alt="User" class="rounded" />
                    @userEmail
                </span>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
                <form id="logoutForm" class="form-inline">
                    <button id="logout" type="submit" class="nav-link btn btn-link text-dark"
                        asp-controller="Identity"
                        asp-action="Logout">
                        Logout
                    </button>
                </form>
            </li>
        </ul>
    </div>
    <!--выпадающий список с инфой о пользователе и кнопкой logout конец-->
}
else
{
    <form class="form-inline" asp-controller="Identity" asp-action="Login">
        <button id="logout" type="submit" class="btn btn-secondary">
            Login
        </button>
    </form>

}